project:
  type: website

website:
  title: "Handong U / Calvin U exchange"
  navbar:
    left:
      - href: itinerary-calvin.qmd
        text: Itinerary

format:
  html:
    theme:
      - yeti
      - brand
    css: styles.css
    toc: true



